название: Java CI с Maven

включенным: [push, pull_request]

задания:
 сборка:

 запуск: ubuntu-последние

    шаги:
 - использование: действия /проверка @ v2
 - название: Настройка
      использования JDK 11: действия / setup-java @ v2
      с:
 java-версия: '11'
        дистрибутив: 'принять'
 - название: Сборка с помощью Maven
      запуск: проверка mvn -B -e
